@@ -0,0 +1,99 @@
﻿<%@ Page Language="VB" MasterPageFile="~/MasterPage.master" AutoEventWireup="false" CodeFile="about us.aspx.vb" Inherits="about_us" title="Untitled Page" %>

<%-- Add content controls here --%><asp:Content ID="Content2" runat="server" 
    contentplaceholderid="head">
    <style type="text/css">
    .MsoNormal
    {
        top: 733px;
        left: 541px;
        position: absolute;
        height: 484px;
        width: 430px;
        font-size: x-large;
    }
    .style32
    {
        font-size: medium;
        color: #003399;
        font-weight: bold;
        text-decoration: underline;
    }
    .style33
    {
        font-size: 14pt;
        font-family: "Adobe Garamond Pro";
    }
    .style34
    {
        font-size: 14pt;
    }
</style>



</asp:Content>
<asp:Content ID="Content3" runat="server" 
    contentplaceholderid="ContentPlaceHolder1">
    <p>
    &nbsp;</p>
<p style="top: 317px; left: 286px; position: absolute; height: 540px; width: 381px">
    <span class="style32">About Us- All you need to know about PetCo</span><br 
        class="style32" />
    <br class="style32" />
    <span class="style33">Petco is a well established pet clinic that specialise in 
    treatment for domestic pets all over Untied Kingdom. We are committed 
    professionals who provide first class treatment for pets and ensure the best 
    possible heatlh care service is being provided. Petco have many branches located 
    in cities such as London, Birmingham, Manchester, Liverpool and many more. Our 
    clinic consists of well-trained staff which are equipped with latest dianostic 
    and therapeutic equipment. </span>
    <br class="style33" />
    <br class="style33" />
    <span class="style33">Employees such as doctors, nurses, security, cleaners and 
    admin staff work directly under the clinic manager who is responsible for the 
    day to day activities. The clinic manager will then report to the director about 
    staff&#39;s performance and will also provide a detailed account on any profits or 
    loss generated by the clinic month.</span><br class="style34" />
</p>
<p>
    &nbsp;</p>
<p>
    <asp:Image ID="Image1" runat="server" ImageUrl="~/Images/petcobuilding.jpg" 
        style="top: 315px; left: 699px; position: absolute; height: 237px; width: 245px" />
    </p>
<p>
    &nbsp;</p>
<p>
    &nbsp;</p>
<p>
    &nbsp;</p>
<p>
    &nbsp;</p>
<p>
    &nbsp;</p>
<p>
    <asp:Image ID="Image2" runat="server" 
        ImageUrl="~/Images/Brent Knoll Animal Centre Site C 26-01-2006.jpg" 
        style="top: 608px; left: 701px; position: absolute; height: 207px; width: 245px" />
    </p>
<p>
    &nbsp;</p>
<p>
    &nbsp;</p>
<p>
    &nbsp;</p>
<p>
    &nbsp;</p>
<p>
    &nbsp;</p>
<p>
    &nbsp;</p>
<p>
    &nbsp;</p>
<p>
    &nbsp;</p>
<p>
    &nbsp;</p>
</asp:Content>
